<!DOCTYPE html>
<html lang="de">
<head lang = "de">
    <meta charset="UTF-8">
    <title>Chat zeigen</title>
    <link rel="stylesheet" href="/css/reset.css">
    <link rel="stylesheet" href="/css/variables.css">
    <link rel="stylesheet" href="/css/base.css">
    <link rel="stylesheet" href="/css/components.css">
</head>
<#import "layout.ftlh" as base>
<@base.layout>
    <h1 class="headline">Support</h1>
    <section class="text-section">
        <p>Willkommen auf der Support-Seite von ProxyParcelBox! Wir sind hier, um Ihnen zu helfen und sicherzustellen,
            dass Sie das Beste aus unserer Plattform herausholen. Sollten Sie auf Probleme stoßen oder Fragen haben,
            finden Sie hier verschiedene Möglichkeiten, Unterstützung zu erhalten. Wenn ihre Fragen nicht beantwortet werden,
            schreiben Sie doch gerne eine Mail an Mia Henrichsmeyer.</p>
        <h3>Häufig gestellte Fragen (FAQ)</h3>
        <ul>
            <li>
                <h4>1. Wie trete ich mit dem Nachbarn in Kontakt, der mein Paket angenommen hat?</h4>
                <p>Nachdem Sie die Sendungsnummer eingegeben haben, wird Ihnen die Kontaktmöglichkeit angezeigt.
                    Sie können direkt über unsere Plattform eine Nachricht an Ihren Nachbarn senden.</p>
            </li>
            <li>
                <h4>2. Wie kann ich den Chat abonnieren, um Benachrichtigungen zu erhalten?</h4>
                <p>Über den "Chat abonnieren" Button im Chat Fenster können Sie ganz einfach den Chat abonnieren.
                    Geben Sie Ihre E-Mail Adresse an und Sie erhalten Benachrichtigungen,
                    wenn Ihr Nachbar eine neue Nachricht gesendet hat.</p>
            </li>
            <li>
                <h4>3. Was kann ich tun, wenn ich meine Sendungsnummer nicht mehr finde?</h4>
                <p>Kontaktieren Sie den Absender des Pakets oder das Versandunternehmen, um die Sendungsnummer erneut zu erhalten.</p>
            </li>
        </ul>
    </section>
</@base.layout>
</html>