<!DOCTYPE html>
<html lang="de">
<head lang = "de">
    <meta charset="UTF-8">
    <title>Chat zeigen</title>
    <link rel="stylesheet" href="/css/reset.css">
    <link rel="stylesheet" href="/css/variables.css">
    <link rel="stylesheet" href="/css/base.css">
    <link rel="stylesheet" href="/css/components.css">
</head>
<#import "layout.ftlh" as base>
<@base.layout>
    <h1 class="headline">Über uns</h1>
    <section class="text-section">
    <p>Willkommen bei ProxyParcelBox, Ihrem zuverlässigen Nachbarschafts-Paketdienst!
        Dieses innovative Projekt wurde im Auftrag unserer Universität entwickelt und zielt darauf ab,
        die Kommunikation und Zusammenarbeit zwischen Nachbarn zu verbessern, wenn es um die Annahme von Paketen geht. </p>
    <h3>Unsere Mission</h3>
    <p>Bei ProxyParcelBox möchten wir sicherstellen, dass Ihre Pakete stets sicher ankommen
        und Sie diese so schnell wie möglich in den Händen halten. Wir verstehen, dass es manchmal schwierig sein kann,
        zur richtigen Zeit zu Hause zu sein, um ein Paket entgegenzunehmen. Deshalb haben wir eine Lösung entwickelt,
        die das Abholen von Paketen bei hilfsbereiten Nachbarn erleichtert.</p>
    <h3>Was wir tun</h3>
    <p>Mit ProxyParcelBox können Sie die Sendungsnummer Ihres Pakets auf unserer Website eingeben
        und sofort den Kontakt mit dem Nachbarn herstellen, der Ihr Paket entgegengenommen hat.
        Unser benutzerfreundliches System ermöglicht es Ihnen, schnell und einfach zu sehen,
        wer Ihr Paket angenommen hat und mit dieser Person in Kontakt zu treten.</p>
    <h3>Chat Abonnieren</h3>
    <p>Neben der Basisfunktionalität bietet ProxyParcelBox auch die Möglichkeit, den Chatverlauf zu abonnieren.
        Dies bedeutet, dass Sie automatisch benachrichtigt werden, wenn neue Nachrichten eingehen.
        So bleiben Sie stets auf dem Laufenden und können schneller auf Mitteilungen Ihrer Nachbarn reagieren.</p>
    <h3>Unser Team</h3>
    <p>Dieses Projekt wurde von Mia Henrichsmeyer im Rahmen des Moduls "Frameworks, Daten und Dienste im Web" erstellt.
        Unser Ziel ist es, reale Probleme mit praktischen und innovativen Lösungen zu adressieren.
        Wir sind stolz darauf, wie ProxyParcelBox das Leben in der Nachbarschaft einfacher und sicherer machen kann.</p>
    <h3>Kontakt</h3>
    <p>Haben Sie Fragen oder Anregungen? Zögern Sie nicht, uns zu kontaktieren.
        Wir freuen uns über Ihr Feedback und sind stets bemüht, unseren Service weiter zu verbessern.
        Vielen Dank, dass Sie ProxyParcelBox nutzen. Gemeinsam machen wir das Paketempfangen einfacher und sicherer!</p>
    </section>
</@base.layout>
</html>